runtime: nodejs
vm: true

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://heroku_b2bqs7tf:fletekbphl10m0alc6ff3u5bod@ds153669.mlab.com:53669/heroku_b2bqs7tf
  APP_ID: fde3a43c-8f25-44e6-8aa8-3923d78338f1
  MASTER_KEY: f1pwD8yE9hRFQrlFXA3SUosh9lgSAATT
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
   PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  